Fixed lost plugin and remove implicity_wait
WebDriverException: Message: 'geckodriver' executable needs to be in
PATH

http://stackoverflow.com/questions/40188699/webdriverexception-message-g
eckodriver-executable-needs-to-be-in-path

1. Install geckodirver at
https://github.com/mozilla/geckodriver/releases
2. Export your file dir with:
export PATH=$PATH:/path/to/geckodriver_folder
Ref:
https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver